from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any
from pathlib import Path

DISCLAIMER = (
    "IMPORTANT: This report is generated by EpiSense as a screening aid only. "
    "It does not constitute a clinical diagnosis. All results must be reviewed "
    "and interpreted by a licensed medical professional before any clinical "
    "decision is made. EpiSense accepts no liability for decisions made solely "
    "on the basis of this report produced by ML mission assets."
)

class ClinicalReportPDF(FPDF):
    def __init__(self, district: str = "Central Command"):
        super().__init__()
        self.district = district

    def header(self):
        # Tactical Border
        self.rect(5, 5, 200, 287)
        
        # Logo placeholder or Title
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(220, 38, 38) # EpiSense Primary Red
        self.cell(0, 15, "EPISENSE HEALTH INTELLIGENCE", ln=True, align="C")
        
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "CLINICAL SCREENING ASSESSMENT", ln=True, align="C")
        
        self.ln(5)
        self.set_font("Helvetica", size=8)
        self.set_text_color(120, 120, 120)
        gen_time = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        self.cell(0, 5, f"DISTRICT: {self.district}  |  GENERATED: {gen_time}  |  CONFIDENTIAL: MISSION LEVEL 2", align="C")
        self.ln(10)

    def footer(self):
        # Disclaimer box at bottom
        self.set_y(-35)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(130, 130, 130)
        self.set_fill_color(245, 245, 245)
        self.multi_cell(0, 4, DISCLAIMER, border=1, align="C", fill=True)
        
        # Page Number
        self.set_y(-15)
        self.set_font("Helvetica", size=8)
        self.cell(0, 10, f"Page {self.page_no()} | EpiSense Intelligence Platform", align="C")

    def add_prediction_result(self, result: Dict[str, Any]):
        self.add_page()
        
        # Summary Header
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, f"Condition: {result['disease'].replace('_', ' ').title()}", ln=True)
        
        # Visual Divider
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        # Risk Assessment Section
        self.set_font("Helvetica", "B", 11)
        self.cell(40, 10, "Risk Index:", ln=False)
        
        # Color score based on tier
        tier = result.get("risk_tier", "LOW")
        if tier == "HIGH": self.set_text_color(220, 38, 38)
        elif tier == "MEDIUM": self.set_text_color(245, 158, 11)
        else: self.set_text_color(22, 163, 74)
        
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, f"{tier} ({result['risk_score']*100:.1f}%)", ln=True)
        
        self.set_text_color(30, 30, 30)
        self.ln(2)
        
        # Clinical Guidance
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, "Tactical Advice:", ln=True)
        self.set_font("Helvetica", size=10)
        self.multi_cell(0, 6, result['advice'])
        self.ln(5)
        
        # Technical Metadata
        self.set_fill_color(250, 250, 250)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, "Technical Traceability", ln=True, fill=True)
        
        self.set_font("Helvetica", size=9)
        self.cell(50, 6, "Model Version:", ln=False)
        self.cell(0, 6, result["model_version"], ln=True)
        
        self.cell(50, 6, "Training Context:", ln=False)
        self.cell(0, 6, f"Data period prior to {result['trained_on']}", ln=True)
        
        self.cell(50, 6, "Screening Timestamp:", ln=False)
        self.cell(0, 6, result["screened_at"], ln=True)
        
        self.cell(50, 6, "Verification Hash:", ln=False)
        self.set_font("Courier", size=7)
        # We don't have the hash here, but could pass it if we wanted full chain. 
        # Using a placeholder for internal audit tag.
        self.cell(0, 6, f"INT-AUDIT-{datetime.now().strftime('%y%m%d')}-00X", ln=True)

class ReportService:
    @staticmethod
    def generate_clinical_report(results: list, district: str = "Central Command") -> bytes:
        pdf = ClinicalReportPDF(district)
        for res in results:
            pdf.add_prediction_result(res)
        return pdf.output()
