import json
from datetime import datetime
from typing import Optional, List
from sqlalchemy import select, and_
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.scenario import Scenario, ScenarioEvent, SimulationState
from app.models.audit_log import PredictionAuditLog
from app.models.alert import Alert, AlertStatus
from app.services.alert_service import AlertService
from app.core.config import settings

class SimulationService:
    @staticmethod
    async def create_simulation(db: AsyncSession, scenario_id: str, user_id: str) -> SimulationState:
        """Initialize a new simulation mission for an officer."""
        sim = SimulationState(
            scenario_id=scenario_id,
            user_id=user_id,
            current_day=0,
            is_active=True
        )
        db.add(sim)
        await db.commit()
        await db.refresh(sim)
        return sim

    @staticmethod
    async def advance_day(db: AsyncSession, simulation_id: str) -> Optional[SimulationState]:
        """Snapshot playback engine: Advances one mission day and triggers all day-offset events."""
        query = select(SimulationState).where(SimulationState.id == simulation_id).with_for_update()
        result = await db.execute(query)
        sim = result.scalar_one_or_none()
        
        if not sim or not sim.is_active:
            return None
            
        # Get scenario to check total days
        scenario_query = select(Scenario).where(Scenario.id == sim.scenario_id)
        scenario_res = await db.execute(scenario_query)
        scenario = scenario_res.scalar_one()

        if sim.current_day >= scenario.total_days:
            sim.is_active = False
            await db.commit()
            return sim

        # Advance Day
        sim.current_day += 1
        
        # Process Events for the new day
        event_query = select(ScenarioEvent).where(
            and_(
                ScenarioEvent.scenario_id == sim.scenario_id,
                ScenarioEvent.day_offset == sim.current_day
            )
        )
        events_res = await db.execute(event_query)
        events = events_res.scalars().all()

        for event in events:
            if event.event_type == "CLINICAL_SURGE":
                # Inject 6 HIGH risk screenings to trigger a cluster alert immediately
                for i in range(6):
                    audit = PredictionAuditLog(
                        user_id=sim.user_id,
                        district_id=event.district_id,
                        endpoint=f"clinical/{event.disease}",
                        input_hash=f"sim_{sim.id}_{sim.current_day}_{i}",
                        risk_score=event.data_json.get("risk_score", 0.85),
                        status="SUCCESS",
                        model_version="sim-v1",
                        timestamp=datetime.utcnow()
                    )
                    db.add(audit)
                
                # Immediate Evaluation (Push logic)
                await AlertService.evaluate_clinical_cluster(db, event.district_id, event.disease)

            elif event.event_type == "FORECAST_SPIKE":
                # Create a pseudo-alert directly from the simulation engine
                new_alert = Alert(
                    district_id=event.district_id,
                    disease=event.disease,
                    risk_score=event.data_json.get("risk_score", 0.92),
                    alert_type="autonomous",
                    status="triggered",
                    metadata_json=json.dumps({"source": "simulation", "day": sim.current_day})
                )
                db.add(new_alert)

        await db.commit()
        await db.refresh(sim)
        return sim

    @staticmethod
    async def reset_simulation(db: AsyncSession, simulation_id: str):
        query = select(SimulationState).where(SimulationState.id == simulation_id).with_for_update()
        result = await db.execute(query)
        sim = result.scalar_one_or_none()
        if sim:
            sim.current_day = 0
            sim.is_active = True
            # Note: In a real system, we'd also clean up alerts generated by THIS simulation
            await db.commit()
            return sim
        return None
