"""make_alert_fields_nullable

Revision ID: 0d76c7c14a2b
Revises: f95b70080308
Create Date: 2026-05-14 12:40:49.632148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d76c7c14a2b'
down_revision: Union[str, None] = 'f95b70080308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'prediction_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alerts', 'acknowledged_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alerts', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('alerts', 'acknowledged_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('alerts', 'prediction_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
