"""add_district_unique_constraint

Revision ID: 7de848ad61ea
Revises: 878db43361c1
Create Date: 2026-05-14 12:39:34.974220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de848ad61ea'
down_revision: Union[str, None] = '878db43361c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uix_district_name_state', 'districts', ['name', 'state_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_district_name_state', 'districts', type_='unique')
    op.drop_column('districts', 'updated_at')
    # ### end Alembic commands ###
