"""add_model_metrics_table

Revision ID: 865b58ceaac0
Revises: 0d76c7c14a2b
Create Date: 2026-05-14 12:46:37.434017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865b58ceaac0'
down_revision: Union[str, None] = '0d76c7c14a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mae', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rmse', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('f1_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_model_version'), 'model_metrics', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_metrics_model_version'), table_name='model_metrics')
    op.drop_table('model_metrics')
    # ### end Alembic commands ###
