"""initial_schema

Revision ID: 878db43361c1
Revises: 
Create Date: 2026-05-14 12:35:41.178514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878db43361c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('area_km2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('population_density', sa.Numeric(precision=10, scale=2), sa.Computed('population / NULLIF(area_km2, 0)', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_state_code'), 'districts', ['state_code'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OFFICER', 'ANALYST', 'VIEWER', 'SYSADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('environmental_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'date', name='uix_env_district_date')
    )
    op.create_index(op.f('ix_environmental_data_date'), 'environmental_data', ['date'], unique=False)
    op.create_index(op.f('ix_environmental_data_district_id'), 'environmental_data', ['district_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risktier'), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('shap_values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'disease', 'prediction_date', name='uix_pred_district_disease_date')
    )
    op.create_index('ix_prediction_district_disease_date', 'predictions', ['district_id', 'disease', sa.text('prediction_date DESC')], unique=False)
    op.create_index(op.f('ix_predictions_district_id'), 'predictions', ['district_id'], unique=False)
    op.create_index(op.f('ix_predictions_pipeline_run_id'), 'predictions', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('confirmed_cases', sa.Integer(), nullable=False),
    sa.Column('suspected_cases', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('IDSP', 'IHIP', 'MANUAL', 'SYNTHETIC', name='datasource'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'disease', 'week_start_date', name='uix_raw_data_district_disease_date')
    )
    op.create_index('ix_raw_data_district_disease_week', 'raw_data', ['district_id', 'disease', sa.text('week_start_date DESC')], unique=False)
    op.create_index(op.f('ix_raw_data_district_id'), 'raw_data', ['district_id'], unique=False)
    op.create_index(op.f('ix_raw_data_week_start_date'), 'raw_data', ['week_start_date'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('adjusted_inputs', sa.JSON(), nullable=False),
    sa.Column('simulated_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_district_id'), 'scenarios', ['district_id'], unique=False)
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('vaccination_coverage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('coverage_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'disease', 'as_of_date', name='uix_vacc_district_disease_date')
    )
    op.create_index(op.f('ix_vaccination_coverage_district_id'), 'vaccination_coverage', ['district_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', name='alertstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_acknowledged_by', 'alerts', ['acknowledged_by'], unique=False, postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.create_index('ix_alert_status_triggered_at', 'alerts', ['status', sa.text('triggered_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_district_id'), 'alerts', ['district_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_id'), table_name='alerts')
    op.drop_index('ix_alert_status_triggered_at', table_name='alerts')
    op.drop_index('ix_alert_acknowledged_by', table_name='alerts', postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.drop_table('alerts')
    op.drop_index(op.f('ix_vaccination_coverage_district_id'), table_name='vaccination_coverage')
    op.drop_table('vaccination_coverage')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_district_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_raw_data_week_start_date'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_district_id'), table_name='raw_data')
    op.drop_index('ix_raw_data_district_disease_week', table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_pipeline_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_district_id'), table_name='predictions')
    op.drop_index('ix_prediction_district_disease_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_token_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_environmental_data_district_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_date'), table_name='environmental_data')
    op.drop_table('environmental_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_districts_state_code'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
