"""make_pipeline_run_fields_nullable

Revision ID: f95b70080308
Revises: 7de848ad61ea
Create Date: 2026-05-14 12:40:24.296078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95b70080308'
down_revision: Union[str, None] = '7de848ad61ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_runs', 'rows_ingested',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_runs', 'error_log',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pipeline_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pipeline_runs', 'error_log',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pipeline_runs', 'rows_ingested',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
